### ISSUE TITLE
encrypted communication

### ISSUE THREAD

**Issue by Christoph1111** [markqvist/tncattach#9]
I did
`# Attach interface
sudo tncattach /dev/ttyUSB0 115200 --mtu 400 --noipv6 --noup

# Configure IP addresses for point-to-point link
sudo ifconfig tnc0 10.93.0.1 pointopoint 10.93.0.2
`
how can I easily encrypt this communication?
Regards

Chris

**Comment by jeremyvisser** [comment]
Please be aware that in many countries, encryption over amateur radio is not legal (or only allowed under certain circumstances, e.g. in Australia encryption is only allowed if it’s for remotely administering a station).

That being said, in case encryption is legal for your use case, you’ve got two main approaches:

- Use encryption at the application layer. For example, use TLS (i.e. use HTTPS instead of HTTP) or SSH.
- Use network layer encryption like WireGuard, OpenVPN, or IPsec.

It’s not tncattach’s responsibility to provide encryption so I would recommend that this ticket be closed.
